const FILE_UPLOAD = "FILE_UPLOAD";
const TABLE_EDIT_ROW = "TABLE_EDIT_ROW";
const TABLE_DELETE_ROW = "TABLE_DELETE_ROW";
const TABLE_ADD_ROW = "TABLE_ADD_ROW";
const TABLE_FILTER_BY_COLOMN = "TABLE_FILTER_BY_COLOMN";
const TABLE_FILTER_BY_SEARCH = "TABLE_FILTER_BY_SEARCH";

export {
  FILE_UPLOAD,
  TABLE_EDIT_ROW,
  TABLE_DELETE_ROW,
  TABLE_ADD_ROW,
  TABLE_FILTER_BY_COLOMN,
  TABLE_FILTER_BY_SEARCH,
};
